/*
 * Copyright 2013, 2014 EnergyOS.org
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.27 at 01:43:57 PM EDT 
//

package org.energyos.espi.common.domain;

import java.util.Calendar;
import java.util.GregorianCalendar;

public class AtomPeriod {

	private static GregorianCalendar mindate=new GregorianCalendar(2000,0,1);
	private static GregorianCalendar maxdate=new GregorianCalendar(9999,0,1);
	public AtomPeriod() {
		super();
		updatedMin = new GregorianCalendar(mindate.get(Calendar.YEAR),mindate.get(Calendar.MONTH),mindate.get(Calendar.DAY_OF_MONTH));
		updatedMax = new GregorianCalendar(maxdate.get(Calendar.YEAR),maxdate.get(Calendar.MONTH),maxdate.get(Calendar.DAY_OF_MONTH));

		publishedMin = new GregorianCalendar(mindate.get(Calendar.YEAR),mindate.get(Calendar.MONTH),mindate.get(Calendar.DAY_OF_MONTH));
		publishedMax = new GregorianCalendar(maxdate.get(Calendar.YEAR),maxdate.get(Calendar.MONTH),maxdate.get(Calendar.DAY_OF_MONTH));
	}

	public boolean isFilterOnPublished() {
		return publishedMin.after(mindate);
	}
	public boolean isFilterOnUpdated() {
		return updatedMin.after(mindate);
	}
	public boolean isFilterOnUsage() {
		return usageMin>0;
	}

	private GregorianCalendar updatedMin = null;
	private GregorianCalendar updatedMax = null;

	private GregorianCalendar publishedMin = null;
	private GregorianCalendar publishedMax = null;
	
	private long usageMin=0;
	private long usageMax=Long.MAX_VALUE;

	public long getUsageMin() {
		return usageMin;
	}

	public void setUsageMin(long usageMin) {
		this.usageMin = usageMin;
	}

	public long getUsageMax() {
		return usageMax;
	}

	public void setUsageMax(long usageMax) {
		this.usageMax = usageMax;
	}

	public GregorianCalendar getUpdatedMin() {
		return updatedMin;
	}

	public void setUpdatedMin(GregorianCalendar updatedMin) {
		this.updatedMin = updatedMin;
	}

	public GregorianCalendar getUpdatedMax() {
		return updatedMax;
	}

	public void setUpdatedMax(GregorianCalendar updatedMax) {
		this.updatedMax = updatedMax;
	}

	public GregorianCalendar getPublishedMin() {
		return publishedMin;
	}

	public void setPublishedMin(GregorianCalendar publishedMin) {
		this.publishedMin = publishedMin;
	}

	public GregorianCalendar getPublishedMax() {
		return publishedMax;
	}

	public void setPublishedMax(GregorianCalendar publishedMax) {
		this.publishedMax = publishedMax;
	}
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(" updated-min "+updatedMin.getTime() );
		sb.append(" updated-max "+updatedMax.getTime() );
		sb.append(" published-min "+publishedMin.getTime()  );
		sb.append(" published-max "+publishedMax.getTime()  );
		sb.append(" usage-min "+usageMin);
		sb.append(" usage-max "+usageMax);
		sb.append(" isFilterOnPublished "+isFilterOnPublished());
		sb.append(" isFilterOnUpdated "+isFilterOnUpdated());
		sb.append(" isFilterOnUsage "+isFilterOnUsage());
		return sb.toString();
	}

}
