/*
 * Copyright 2013, 2014 EnergyOS.org
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.27 at 01:43:57 PM EDT 
//

package org.energyos.espi.common.domain;

import java.util.Date;

public class AtomPeriod {

	private static Date mindate=new Date(2000-1900,0,1);
	public AtomPeriod() {
		super();
		updatedMin = new Date(mindate.getTime());
		//updatedMin.set(2000, 0, 1);
		updatedMax = new Date();

		publishedMin = new Date(mindate.getTime());
		//publishedMin.set(2000, 0, 1);
		publishedMax = new Date();
	}

	public boolean isFilterOnPublished() {
		return publishedMin.after(mindate);
	}
	public boolean isFilterOnUpdated() {
		return updatedMin.after(mindate);
	}
	public boolean isFilterOnUsage() {
		return usageMin>0;
	}

	private Date updatedMin = null;
	private Date updatedMax = null;

	private Date publishedMin = null;
	private Date publishedMax = null;
	
	private long usageMin=0;
	private long usageMax=Long.MAX_VALUE;

	public long getUsageMin() {
		return usageMin;
	}

	public void setUsageMin(long usageMin) {
		this.usageMin = usageMin;
	}

	public long getUsageMax() {
		return usageMax;
	}

	public void setUsageMax(long usageMax) {
		this.usageMax = usageMax;
	}

	public Date getUpdatedMin() {
		return updatedMin;
	}

	public void setUpdatedMin(Date updatedMin) {
		this.updatedMin = updatedMin;
	}

	public Date getUpdatedMax() {
		return updatedMax;
	}

	public void setUpdatedMax(Date updatedMax) {
		this.updatedMax = updatedMax;
	}

	public Date getPublishedMin() {
		return publishedMin;
	}

	public void setPublishedMin(Date publishedMin) {
		this.publishedMin = publishedMin;
	}

	public Date getPublishedMax() {
		return publishedMax;
	}

	public void setPublishedMax(Date publishedMax) {
		this.publishedMax = publishedMax;
	}
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(" updated-min "+updatedMin.getTime() + " "+updatedMin );
		sb.append(" updated-max "+updatedMax.getTime() + " "+updatedMax );
		sb.append(" published-min "+publishedMin.getTime() + " "+publishedMin );
		sb.append(" published-max "+publishedMax.getTime() + " "+publishedMax );
		sb.append(" usage-min "+usageMin);
		sb.append(" usage-max "+usageMax);
		sb.append(" isFilterOnPublished "+isFilterOnPublished());
		sb.append(" isFilterOnUpdated "+isFilterOnUpdated());
		sb.append(" isFilterOnUsage "+isFilterOnUsage());
		return sb.toString();
	}

}
