/*
 * Copyright 2013 EnergyOS.org
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.27 at 01:43:57 PM EDT 
//


package org.energyos.espi.common.domain;

import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.energyos.espi.common.models.atom.adapters.CustomerAdapter;



@XmlRootElement(name="ServiceLocation", namespace="http://naesb.org/espi")
@XmlJavaTypeAdapter(CustomerAdapter.class)
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceLocation")
@Entity
@Table(name = "service_location")
@NamedQueries(value = {
        @NamedQuery(name = ServiceLocation.QUERY_FIND_ALL_IDS,
                query = "SELECT serviceLocation.id FROM ServiceLocation serviceLocation"),		
        @NamedQuery(name = ServiceLocation.QUERY_FIND_BY_ID, 
        		query = "SELECT serviceLocation FROM ServiceLocation serviceLocation WHERE serviceLocation.id = :id"),
        		
        		
        @NamedQuery(name = ServiceLocation.QUERY_FIND_BY_RETAILCUSTOMER_ID_CUSTOMER_ID_ACCOUNT_ID_AGREEMENT_ID_LOCATION_ID, query = "SELECT serviceLocation FROM ServiceLocation serviceLocation WHERE serviceLocation.customerAgreement.customerAccount.customer.retailCustomerId =:retailCustomerId and serviceLocation.customerAgreement.customerAccount.customer.id = :customerId and serviceLocation.customerAgreement.customerAccount.id =:accountId and serviceLocation.customerAgreement.id =:agreementId and serviceLocation.id = :serviceLocationId"),
        		
        @NamedQuery(name = ServiceLocation.QUERY_FIND_BY_RETAILCUSTOMER_ID_CUSTOMER_ID_ACCOUNT_ID_AGREEMENT_ID, query = "SELECT serviceLocation FROM ServiceLocation serviceLocation WHERE serviceLocation.customerAgreement.customerAccount.customer.retailCustomerId =:retailCustomerId and serviceLocation.customerAgreement.customerAccount.customer.id = :customerId and serviceLocation.customerAgreement.customerAccount.id =:accountId and serviceLocation.customerAgreement.id =:agreementId"),
        		
        		
        		
       @NamedQuery(name = ServiceLocation.QUERY_FIND_BY_CUSTOMER_ID_CUSTOMER_ACCOUNT_ID_CUSTOMER_AGREEMENT_ID, 
         		query = "SELECT serviceLocation FROM ServiceLocation serviceLocation WHERE serviceLocation.customerAgreement.customerAccount.customer.id = :customerId and serviceLocation.customerAgreement.customerAccount.id =:customerAccountId and serviceLocation.customerAgreement.id =:customerAgreementId"),
              
})  
public class ServiceLocation extends IdentifiedObject 
        {

    public static final String QUERY_FIND_ALL_IDS = "ServiceLocation.findAllIds";
    public static final String QUERY_FIND_BY_ID = "ServiceLocation.findById";
    public static final String QUERY_FIND_BY_CUSTOMER_ID_CUSTOMER_ACCOUNT_ID_CUSTOMER_AGREEMENT_ID = "ServiceLocation.findByCustomerIdCustomerAccountIdCustomerAgreementId";
    
    
    public static final String QUERY_FIND_BY_RETAILCUSTOMER_ID_CUSTOMER_ID_ACCOUNT_ID_AGREEMENT_ID_LOCATION_ID = "ServiceLocation.findByRetailCustomerIdCustomerIdAccountIdAgreementIdServiceLocationId";
    
    public static final String QUERY_FIND_BY_RETAILCUSTOMER_ID_CUSTOMER_ID_ACCOUNT_ID_AGREEMENT_ID = "ServiceLocation.findByRetailCustomerIdCustomerIdAccountIdAgreementId";
    
    @Column(name = "name")
    protected String name;    
    
    @Column(name = "type")
    protected String type; 
    
    @Column(name = "enabled")
    protected boolean enabled; 
    
    @XmlTransient
    @Column(name = "usage_point_ref")
    protected Long usagePointRef; 
    
	@OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "main_address")
	protected Address mainAddress;
    
	@OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "secondary_address")
	protected Address secondaryAddress;
    
    @Embedded
    @AttributeOverrides({
    	@AttributeOverride(name="countryCode", column=@Column(name="phone1_country_code")),
    	@AttributeOverride(name="areaCode", column=@Column(name="phone1_area_code")),
    	@AttributeOverride(name="cityCode", column=@Column(name="phone1_city_code")),
    	@AttributeOverride(name="extension", column=@Column(name="phone1_extension")),
    	@AttributeOverride(name="localNumber", column=@Column(name="phone1_local_number"))
    	
    })
	protected TelephoneNumber phone1;
    
    @Embedded
    @AttributeOverrides({
    	@AttributeOverride(name="countryCode", column=@Column(name="phone2_country_code")),
    	@AttributeOverride(name="areaCode", column=@Column(name="phone2_area_code")),
    	@AttributeOverride(name="cityCode", column=@Column(name="phone2_city_code")),
    	@AttributeOverride(name="extension", column=@Column(name="phone2_extension")),
    	@AttributeOverride(name="localNumber", column=@Column(name="phone2_local_number"))
    	
    })
	protected TelephoneNumber phone2;
    
   /* @Column(name = "electronic_address")
	protected String electronicAddress;*/
    
    @Embedded
    ElectronicAddress electronicAddress;
    
    @Column(name = "goInfo_reference")
	protected String goInfoReference;
    
    @Column(name = "direction")
	protected String direction;
    
    
    @Embedded
	protected Status status;
    
    @Column(name = "access_method")
	protected String access_method;
    
    @Column(name = "siteAccess_mroblem")
	protected String siteAccessProblem;
    
    @Column(name = "needs_inspection")
	protected String needsInspection;
    
    @Embedded
	protected PositionPoint positionPoint;
    
 
    
    
    @Embedded
    @Transient
    protected UsagePoints usagePoints; 
    
   /* @Column(name = "usagePointId")
    protected long usagePointId;*/
    
   
     public boolean isEnabled() {
 	return enabled;
 }


 public void setEnabled(boolean enabled) {
 	this.enabled = enabled;
 }
    
   /* @Embedded
  	protected Status status;*/
    
    
    @XmlTransient
    @Transient
    private String link;
  
    @XmlTransient
   	@ManyToOne(fetch=FetchType.EAGER)
   	@JoinColumn(name = "customer_agreement_id")
   	private CustomerAgreement customerAgreement;
    
    
    public String getLink() {
    	if(customerAgreement!=null)
    		return this.customerAgreement.getLink()+"/CustomerAgreement/"+this.customerAgreement.getId();
    	else 
    		return null;
	}




	public void setLink(Long customerId, Long accountId, Long agreementId) {
		this.link = "/Customer/"+customerId+"/CustomerAccount/"+accountId+"/CustomerAgreement/"+agreementId;
	}




	public ServiceLocation() {
		super();
		//
		//this.usagePoint = new UsagePoint();
	}
    
    
    
    
    public String getName() {
		return name;
	}



	public void setName(String name) {
		this.name = name;
	}



	public String getType() {
		return type;
	}





	public void setType(String type) {
		this.type = type;
	}


	public CustomerAgreement getCustomerAgreement() {
        return customerAgreement;
    }

    public void setCustomerAgreement(CustomerAgreement customerAgreement) {
        this.customerAgreement = customerAgreement;
    }
    
    
    @XmlTransient
	@OneToMany(fetch = FetchType.EAGER, mappedBy= "serviceLocation" ,cascade = CascadeType.REMOVE)
    private Set<EndDevice> endDevices;
    

   /* @Transient
    private UsagePoint usagePoint = new UsagePoint() ;*/
   
	
    
   
	public Set<EndDevice> getEndDevices() {
		return endDevices;
	}


	public void setEndDevices(Set<EndDevice> endDevices) {
		this.endDevices = endDevices;
	}

  

	/*public UsagePoint getUsagePoint() {
		return usagePoint;
	}



	public void setUsagePoint(UsagePoint usagePoint) {
		this.usagePoint = usagePoint;
	}*/




	@Override
	public String toString() {
		return "ServiceLocation [name=" + name + "]";
	}


	public Long getUsagePointRef() {
		return usagePointRef;
	}


	public void setUsagePointRef(Long usagePointRef) {
		this.usagePointRef = usagePointRef;
	}




	public UsagePoints getUsagePoints() {
		return usagePoints;
	}


	public void setUsagePoints(UsagePoints usagePoints) {
		this.usagePoints = usagePoints;
	}



	public Address getMainAddress() {
		return mainAddress;
	}


	public void setMainAddress(Address mainAddress) {
		this.mainAddress = mainAddress;
	}


	public Address getSecondaryAddress() {
		return secondaryAddress;
	}


	public void setSecondaryAddress(Address secondaryAddress) {
		this.secondaryAddress = secondaryAddress;
	}


	public TelephoneNumber getPhone1() {
		return phone1;
	}


	public void setPhone1(TelephoneNumber phone1) {
		this.phone1 = phone1;
	}


	public TelephoneNumber getPhone2() {
		return phone2;
	}


	public void setPhone2(TelephoneNumber phone2) {
		this.phone2 = phone2;
	}


	public ElectronicAddress getElectronicAddress() {
		return electronicAddress;
	}


	public void setElectronicAddress(ElectronicAddress electronicAddress) {
		this.electronicAddress = electronicAddress;
	}


	public String getGoInfoReference() {
		return goInfoReference;
	}


	public void setGoInfoReference(String goInfoReference) {
		this.goInfoReference = goInfoReference;
	}


	public String getDirection() {
		return direction;
	}


	public void setDirection(String direction) {
		this.direction = direction;
	}


	public Status getStatus() {
		return status;
	}


	public void setStatus(Status status) {
		this.status = status;
	}


	public String getAccess_method() {
		return access_method;
	}


	public void setAccess_method(String access_method) {
		this.access_method = access_method;
	}


	public String getSiteAccessProblem() {
		return siteAccessProblem;
	}


	public void setSiteAccessProblem(String siteAccessProblem) {
		this.siteAccessProblem = siteAccessProblem;
	}


	public String getNeedsInspection() {
		return needsInspection;
	}


	public void setNeedsInspection(String needsInspection) {
		this.needsInspection = needsInspection;
	}


	public PositionPoint getPositionPoint() {
		return positionPoint;
	}


	public void setPositionPoint(PositionPoint positionPoint) {
		this.positionPoint = positionPoint;
	}

    
}
