/*
 * Copyright 2013 EnergyOS.org
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.27 at 01:43:57 PM EDT 
//

package org.energyos.espi.common.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.energyos.espi.common.models.atom.adapters.CustomerAdapter;

@XmlRootElement(name = "ServiceSupplier", namespace = "http://naesb.org/espi")
@XmlJavaTypeAdapter(CustomerAdapter.class)
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceSupplier")
@Entity
@Table(name = "service_supplier")
@NamedQueries(value = {
		@NamedQuery(name = ServiceSupplier.QUERY_FIND_ALL_IDS, query = "SELECT serviceSupplier.id FROM ServiceSupplier serviceSupplier"),
		@NamedQuery(name = ServiceSupplier.QUERY_FIND_BY_ID, query = "SELECT serviceSupplier FROM ServiceSupplier serviceSupplier WHERE serviceSupplier.id = :id"),
		
	    @NamedQuery(name = ServiceSupplier.QUERY_FIND_BY_RETAILCUSTOMER_ID_CUSTOMER_ID_ACCOUNT_ID_AGREEMENT_ID_SUPPLIER_ID, query = "SELECT serviceSupplier FROM ServiceSupplier serviceSupplier WHERE serviceSupplier.customerAgreement.customerAccount.customer.retailCustomerId =:retailCustomerId and serviceSupplier.customerAgreement.customerAccount.customer.id = :customerId and serviceSupplier.customerAgreement.customerAccount.id =:accountId and serviceSupplier.customerAgreement.id =:agreementId and serviceSupplier.id = :serviceSupplierId"),
 		
	    @NamedQuery(name = ServiceSupplier.QUERY_FIND_BY_RETAILCUSTOMER_ID_CUSTOMER_ID_ACCOUNT_ID_AGREEMENT_ID, query = "SELECT serviceSupplier FROM ServiceSupplier serviceSupplier WHERE serviceSupplier.customerAgreement.customerAccount.customer.retailCustomerId =:retailCustomerId and serviceSupplier.customerAgreement.customerAccount.customer.id = :customerId and serviceSupplier.customerAgreement.customerAccount.id =:accountId and serviceSupplier.customerAgreement.id =:agreementId"),
	        		
	  
		@NamedQuery(name = ServiceSupplier.QUERY_FIND_BY_CUSTOMER_ID_CUSTOMER_ACCOUNT_ID_CUSTOMER_AGREEMENT_ID, query = "SELECT serviceSupplier FROM ServiceSupplier serviceSupplier WHERE serviceSupplier.customerAgreement.customerAccount.customer.id = :customerId and serviceSupplier.customerAgreement.customerAccount.id =:customerAccountId and serviceSupplier.customerAgreement.id =:customerAgreementId"),

})
public class ServiceSupplier extends IdentifiedObject {

	public static final String QUERY_FIND_ALL_IDS = "ServiceSupplier.findAllIds";
	public static final String QUERY_FIND_BY_ID = "ServiceSupplier.findById";
	public static final String QUERY_FIND_BY_CUSTOMER_ID_CUSTOMER_ACCOUNT_ID_CUSTOMER_AGREEMENT_ID = "ServiceSupplier.findByCustomerIdCustomerAccountIdCustomerAgreementId";

    public static final String QUERY_FIND_BY_RETAILCUSTOMER_ID_CUSTOMER_ID_ACCOUNT_ID_AGREEMENT_ID_SUPPLIER_ID = "ServiceSupplier.findByRetailCustomerIdCustomerIdAccountIdAgreementIdServiceSupplierId";
    
    public static final String QUERY_FIND_BY_RETAILCUSTOMER_ID_CUSTOMER_ID_ACCOUNT_ID_AGREEMENT_ID = "ServiceSupplier.findByRetailCustomerIdCustomerIdAccountIdAgreementId";
    
	
	
	@Column(name = "name")
	protected String name;

	@Column(name = "kind")
	protected String kind;
	
	@Column(name = "enabled")
	protected boolean enabled;
	
	

	@Column(name = "issuerIdentificationNumber")
	protected String issuerIdentificationNumber;

	public boolean isEnabled() {
		return enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@XmlTransient
	@Transient
	private String link;

	@XmlTransient
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_agreement_id")
	private CustomerAgreement customerAgreement;

	public String getLink() {
		if(customerAgreement!=null)
			return this.customerAgreement.getLink() + "/CustomerAgreement/"
				+ this.customerAgreement.getId();
		else
			return null;
	}

	public void setLink(Long customerId, Long accountId, Long agreementId) {
		this.link = "/Customer/" + customerId + "/CustomerAccount/" + accountId
				+ "/CustomerAgreement/" + agreementId;
	}

	public ServiceSupplier() {
		super();
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getKind() {
		return kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public String getIssuerIdentificationNumber() {
		return issuerIdentificationNumber;
	}

	public void setIssuerIdentificationNumber(String issuerIdentificationNumber) {
		this.issuerIdentificationNumber = issuerIdentificationNumber;
	}

	public CustomerAgreement getCustomerAgreement() {
		return customerAgreement;
	}

	public void setCustomerAgreement(CustomerAgreement customerAgreement) {
		this.customerAgreement = customerAgreement;
	}

	@Override
	public String toString() {
		return "ServiceSupplier [name=" + name + "]";
	}

	

}
