/*
 * Copyright 2013, 2014 EnergyOS.org
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.27 at 01:43:57 PM EDT 
//

package org.energyos.espi.common.domain;

import java.util.Calendar;

public class AtomPeriod {

	public AtomPeriod() {
		super();
		updatedMin = Calendar.getInstance();
		updatedMin.set(2000, 0, 1);
		updatedMax = Calendar.getInstance();

		publishedMin = Calendar.getInstance();
		publishedMin.set(2000, 0, 1);
		publishedMax = Calendar.getInstance();
	}

	private Calendar updatedMin = null;
	private Calendar updatedMax = null;

	private Calendar publishedMin = null;
	private Calendar publishedMax = null;
	
	private long usageMin=0;
	private long usageMax=Long.MAX_VALUE;

	public long getUsageMin() {
		return usageMin;
	}

	public void setUsageMin(long usageMin) {
		this.usageMin = usageMin;
	}

	public long getUsageMax() {
		return usageMax;
	}

	public void setUsageMax(long usageMax) {
		this.usageMax = usageMax;
	}

	public Calendar getUpdatedMin() {
		return updatedMin;
	}

	public void setUpdatedMin(Calendar updatedMin) {
		this.updatedMin = updatedMin;
	}

	public Calendar getUpdatedMax() {
		return updatedMax;
	}

	public void setUpdatedMax(Calendar updatedMax) {
		this.updatedMax = updatedMax;
	}

	public Calendar getPublishedMin() {
		return publishedMin;
	}

	public void setPublishedMin(Calendar publishedMin) {
		this.publishedMin = publishedMin;
	}

	public Calendar getPublishedMax() {
		return publishedMax;
	}

	public void setPublishedMax(Calendar publishedMax) {
		this.publishedMax = publishedMax;
	}
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("updated-min"+updatedMin.getTime() );
		sb.append("updated-max"+updatedMax.getTime() );
		sb.append("published-min"+publishedMin.getTime() );
		sb.append("published-max"+publishedMax.getTime() );
		sb.append("usage-min"+usageMin);
		sb.append("usage-max"+usageMax);
		return sb.toString();
	}

}
